-- AlterTable
ALTER TABLE "Answer" ALTER COLUMN "time" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Question" ALTER COLUMN "time" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "time" SET DATA TYPE DOUBLE PRECISION;
